skip_operations:
  - CreateIncidentAttachment
  - DeleteIncidentAttachment
  - UpdateIncidentAttachment
  - CreateUserNotificationRule
  - DeleteUserNotificationRule
  - GetUserNotificationRule
  - ListUserNotificationRules
  - UpdateUserNotificationRule
  - MakeGCPSTSDelegate
  - SubmitLog
  - UploadCustomCostsFile
  - CreateTeamNotificationRule
  - DeleteTeamNotificationRule
  - GetTeamNotificationRule
  - GetTeamNotificationRules
  - UpdateTeamNotificationRule
  - CreateAWSAccountCCMConfig
  - GetAWSAccountCCMConfig
  - DeleteAWSAccountCCMConfig
  - UpdateAWSAccountCCMConfig
  - ListIncidentAttachments
  - AddRumReplaySessionToPlaylist
  - RemoveRumReplaySessionFromPlaylist
  - UpdateRumReplaySessionFromPlaylist
  - ListRumReplayPlaylistSessions
  - BulkRemoveRumReplayPlaylistSessions
  - DeleteRumReplayPlaylist
  - GetRumReplayPlaylist
  - UpdateRumReplayPlaylist
  - ListRumReplayPlaylist

optional_parameters_operations:
  SearchCIAppTestEvents: SearchCIAppTestEventsOptionalParameters
  SearchCIAppPipelineEvents: SearchCIAppPipelineEventsOptionalParameters
  SearchAuditLogs: SearchAuditLogsOptionalParameters
  SearchEvents: SearchEventsOptionalParameters
  CreateOpenAPI: CreateOpenAPIOptionalParameters
  UpdateOpenAPI: UpdateOpenAPIOptionalParameters
  ListLogs: ListLogsOptionalParameters
  UploadIdPMetadata: UploadIdPMetadataOptionalParameters
  SearchFlakyTests: SearchFlakyTestsOptionalParameters
  SearchSecurityMonitoringHistsignals: SearchSecurityMonitoringHistsignalsOptionalParameters
  SearchSecurityMonitoringSignals: SearchSecurityMonitoringSignalsOptionalParameters

bundle_aliases:
  actions_datastores:
    - datastores
    - datastore
  action_connection:
    - connection
  application_security:
    - appsec
  cloud_cost_management:
    - ccm
  microsoft_teams_integration:
    - msteams-integration
  networkd_device_monitoring:
    - ndm
  sensitive_data_scanner:
    - sds
  service_level_objectives:
    - slo
  service_scorecards:
    - scorecards
    - scorecard
  workflow_automation:
    - workflow
    - wf

bundle_name_overrides:
  APM: apm
  APMRetentionFilters: apm_retention_filters
  AuthNMappings: authn_mappings
  HighAvailabilityMultiRegion: high_availability_multiregion
  OCIIntegration: oci_integration
  ServiceNowIntegration: servicenow_integration

argument_type_overrides:
  GetCostByOrg:
    start_month: time.Time
  GetHistoricalCostByOrg:
    start_month: time.Time
  GetMonthlyCostAttribution:
    start_month: time.Time
  GetHourlyUsage:
    filter[timestamp][start]: time.Time
  GetUsageApplicationSecurityMonitoring:
    start_hr: time.Time
  GetUsageLambdaTracedInvocations:
    start_hr: time.Time
  GetUsageObservabilityPipelines:
    start_hr: time.Time

response_type_overrides:
  AttachmentArray: IncidentAttachmentsResponse

force_response_operations:
  - GetSignalNotificationRules
  - GetVulnerabilityNotificationRules

acronyms:
  - DORA
  - AD
  - AI
  - APIs
  - API
  - AWS
  - CI
  - GCP
  - CPU
  - CSM
  - DORA
  - IAM
  - ID
  - IP
  - JSON
  - RUM
  - SBOM
  - SCA
  - SLO
  - STS
  - WAF
  - CUR
  - UC
  - SPA
  - LLM
  - CCM
